<?php if (Mage::getStoreConfig('onepage_checkout/general/enable_discount')) : ?>
<div class="checkout-agreements discount" id="discount-coupon-form">
    <?php echo $this->getChildHtml('coupon') ?>
</div>
<?php endif; ?>

<div class="order-review" id="checkout-review-load">
    <?php echo $this->getChildHtml('info') ?>
    <?php echo $this->getChildHtml('order.review', true, true);?>
</div>

<?php if (Mage::getStoreConfig('onepage_checkout/fields_settings/comments')) : ?>
<div id="customer-comments-wrap" class="checkout-agreements">
    <label for="customer_comments"><?php echo $this->__('Comments') ?></label>
    <textarea id="customer_comments" name="customer_comments" rows="5"></textarea>
</div>
<?php endif; ?>

<?php echo $this->getChildHtml('additional') ?>

<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <?php echo $this->getChildHtml('newsletter') ?>
    <div class="buttons-set" id="review-buttons-container">
        <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        review = new Review('checkoutSteps', '<?php echo $this->getUrl('checkout/onepage/saveOrder') ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>');
    //]]>
    </script>
</div>
