<?php if($this->getCurrencyCount()>1): ?>

<div class="box language-switcher" style="margin-left:15px">

<div class="block block-subscribe" style="width:auto;margin-top:0px;">

    <div class="block-title">

    <strong>

    <span>Your Currency</span>

    </strong>

    </div>

    <div class="head_search">
        <select name="currency" onchange="changeCurrency(this)" style="margin:0">

        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>

        <option value="<?php echo $_code ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>

        <?php echo $_name ?> - <?php echo $_code ?>

        </option>

        <?php endforeach; ?>

        </select>
    </div>
</div>

</div>

<script type="text/javascript">

//<![CDATA[

function changeCurrency(sObject){

if(sObject.value){

setLocation('<?php echo $this->helper('directory/url')->getSwitchCurrencyUrl() ?>currency/'+sObject.value);

}

}

//]]>

</script>

<?php endif; ?>